name       : suricata
version    : 4.0.4
release    : 12
source     :
    - https://www.openinfosecfoundation.org/download/suricata-4.0.4.tar.gz : 617e83b6e20b03aa7d5e05a980d3cb6d2810ec18a6f15a36bf66c81c9c0a2abb
license    : GPL-2.0
component  : security
summary    : Suricata is a high performance Network IDS, IPS and Network Security Monitoring engine
description: |
    The Suricata engine is capable of real time intrusion detection (IDS),
    inline intrusion prevention (IPS), network security monitoring (NSM) and
    offline pcap processing.
builddeps  :
    - pkgconfig(htp)
    - pkgconfig(jansson)
    - pkgconfig(libcap-ng)
    - pkgconfig(lua-5.3)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - libpcap-devel
setup      : |
    # Irrelevant txt files are getting installed, drop them
    %patch -p1 < $pkgfiles/suricata-2.0.9-docs.patch

    %reconfigure --disable-static \
               --enable-afl \
               --enable-lua \
               --disable-gccmarch-native \
               --enable-non-bundled-htp \
               --enable-gccprotect \
               --enable-pie \
               --enable-unittests
build      : |
    %make
install    : |
    %make_install

    install -d -m 0755 $installdir/var/log/suricata

    install -D -m 0600 suricata.yaml $installdir/etc/suricata/suricata.yaml
    install -D -m 0600 classification.config $installdir/etc/suricata/classification.config
    install -D -m 0600 reference.config $installdir/etc/suricata/reference.config

    install -d -m 0750 $installdir/etc/suricata/rules
    install -D -m 0600 rules/*.rules $installdir/etc/suricata/rules/

    sed -i "s|#EnvironmentFile=-/etc/default/suricata|EnvironmentFile=-/etc/default/suricata|" etc/suricata.service
    install -D -m 0644 etc/suricata.service $installdir/%libdir%/systemd/system/suricata.service

    install -D -m 0644 $pkgfiles/suricata.tmpfiles $installdir/%libdir%/tmpfiles.d/suricata.conf
check      : |
    %make check

