name       : suricata
version    : 3.1.2
release    : 1
source     :
    - https://www.openinfosecfoundation.org/download/suricata-3.1.2.tar.gz : f9e7742580849f202254e75d9fc245ba53f4d7490f47a6d30f02a7b10aacc512
license    : GPL-2.0
component  : security
summary    : The Suricata engine is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.
description: |
    The Suricata engine is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.
builddeps  :
    - pkgconfig(htp)
    - pkgconfig(jansson)
    - pkgconfig(lua-5.1)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - libpcap-devel
setup      : |
    %configure --enable-afl \
               --enable-lua \
               --enable-non-bundled-htp
build      : |
    %make
install    : |
    %make_install
