name       : suricata
version    : 3.2.1
release    : 3
source     :
    - https://www.openinfosecfoundation.org/download/suricata-3.2.1.tar.gz : 0e0b0cf49016804bb2fb1fc4327341617e76a67902f4e03e0ef6d16c1d7d3994
license    : GPL-2.0
component  : security
summary    : The Suricata engine is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.
description: |
    The Suricata engine is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.
builddeps  :
    - pkgconfig(htp)
    - pkgconfig(jansson)
    - pkgconfig(lua-5.1)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - libpcap-devel
setup      : |
    %configure --enable-afl \
               --enable-lua \
               --enable-non-bundled-htp
build      : |
    %make
install    : |
    %make_install
