name       : suricata
version    : 4.1.1
release    : 15
source     :
    - https://www.openinfosecfoundation.org/download/suricata-4.1.1.tar.gz : c30058072029e7fde09133674d9f2f840a674eecbeae1f8b1779a3aae8166bb0
license    : GPL-2.0-or-later
component  : security
summary    : Suricata is a high performance Network IDS, IPS and Network Security Monitoring engine
description: |
    The Suricata engine is capable of real time intrusion detection (IDS),
    inline intrusion prevention (IPS), network security monitoring (NSM) and
    offline pcap processing.
builddeps  :
    - pkgconfig(htp)
    - pkgconfig(jansson)
    - pkgconfig(libcap-ng)
    - pkgconfig(liblz4)
    - pkgconfig(lua-5.3)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - cargo
    - libpcap-devel
setup      : |
    # Irrelevant txt files are getting installed, drop them
    %patch -p1 < $pkgfiles/suricata-2.0.9-docs.patch

    %reconfigure --disable-static \
               --enable-afl \
               --enable-lua \
               --disable-gccmarch-native \
               --enable-non-bundled-htp \
               --enable-gccprotect \
               --enable-pie \
               --enable-unittests
build      : |
    %make
install    : |
    %make_install

    install -d -m00755 $installdir/var/log/suricata

    install -D -m00600 suricata.yaml $installdir/etc/suricata/suricata.yaml
    install -D -m00600 classification.config $installdir/etc/suricata/classification.config
    install -D -m00600 reference.config $installdir/etc/suricata/reference.config

    install -d -m00750 $installdir/etc/suricata/rules
    install -D -m00600 rules/*.rules $installdir/etc/suricata/rules/

    sed -i "s|#EnvironmentFile=-/etc/default/suricata|EnvironmentFile=-/etc/default/suricata|" etc/suricata.service
    install -D -m00644 etc/suricata.service $installdir/%libdir%/systemd/system/suricata.service

    install -D -m00644 $pkgfiles/suricata.tmpfiles $installdir/%libdir%/tmpfiles.d/suricata.conf
check      : |
    %make check
