name       : suricata
version    : 3.2.2
release    : 5
source     :
    - https://www.openinfosecfoundation.org/download/suricata-3.2.2.tar.gz : b1d8e5e53a76fbc89712d10ca8e2208f68f6fc2def0e6ac82e9693bb586a49cb
license    : GPL-2.0
component  : security
summary    : Suricata is a high performance Network IDS, IPS and Network Security
    Monitoring engine
description: |
    The Suricata engine is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.
builddeps  :
    - pkgconfig(htp)
    - pkgconfig(jansson)
    - pkgconfig(lua-5.1)
    - pkgconfig(nss)
    - pkgconfig(yaml-0.1)
    - libpcap-devel
setup      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %configure --enable-afl \
               --enable-lua \
               --enable-non-bundled-htp \
               --enable-gccprotect \
               --enable-pie
build      : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %make
install    : |
    export CFLAGS="$CFLAGS -I/usr/include/lua5.1"
    %make_install

    install -d -m 0755 $installdir/var/log/suricata

    install -D -m 0600 suricata.yaml $installdir/etc/suricata/suricata.yaml
    install -D -m 0600 classification.config $installdir/etc/suricata/classification.config
    install -D -m 0600 reference.config $installdir/etc/suricata/reference.config

    install -d -m 0750 $installdir/etc/suricata/rules
    install -D -m 0600 rules/*.rules $installdir/etc/suricata/rules/

    install -D -m 0644 $pkgfiles/suricata.service $installdir/%libdir%/systemd/system/suricata.service
    install -D -m 0644 $pkgfiles/suricata.tmpfiles $installdir/%libdir%/tmpfiles.d/suricata.conf
    rm -r $installdir/usr/share/doc
